name: Linux - Build, Test, and Upload

on:
  push:
    # branches: [ main ]
    tags:
      - v*
  # pull_request:
  #   branches: [ main ]

# defaults:
#   run:
#     shell: bash
#     working-directory: ./scripts

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest
    container:
      # https://github.com/pypa/manylinux
      # NOTE: Intel MKL is incompatible with manylinux2014
      image: quay.io/pypa/${{ vars.MANYLINUX_PLATFORM }}

    env:
      # package versions are set in github actions variables:
      #   settings - secrets and variables - actions - variables
      PETSC_ARCH: arch-linux-c-opt-mkl

      # Compile flags (C/CXX/F)
      # -------------
      # generate position independent code (PIC) meaning that it is insensitive to
      # the exact order in which the dynamic libs are loaded
      MPICH_FLAGS: -fPIC
      # we do not want to optimize too much to a specific CPU (march, mtune)
      # fp-model=precise is for MKL otherwise maybe not necessary
      PETSC_FLAGS: -O2 -s -march=x86_64 -fp-model=precise

      # store libraries in here
      LIB_DIR: /custom_libs

      USE_PYTHON_VERSION: cp311

      MPICH_BASE_UR: https://www.mpich.org/static/downloads
      PETSC_BASE_URL: https://web.cels.anl.gov/projects/petsc/download/release-snapshots
      MKL_BASE_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/cdff21a5-6ac7-4b41-a7ec-351b5f9ce8fd

    if: ${{ startsWith(github.ref, 'refs/tags') || !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
      # checkout repository
      # checkout@v4 does not seem to work with containers
      # https://github.com/actions/checkout/issues/1474
    - uses: actions/checkout@v3

    - name: Prepare
      run: |

        mkdir ${{ env.LIB_DIR }}

        # ugly but for testing
        # echo "Adding python to GITHUB_PATH"
        # PYTHON_VERSION=cp311
        # export PATH=/opt/python/cp311-cp311/bin:$PATH


        # export PATH=/opt/python/${{ env.USE_PYTHON_VERSION }}-${{ env.USE_PYTHON_VERSION }}/bin:$PATH
        # echo "PYTHON_PATH=/opt/python/${{ env.USE_PYTHON_VERSION }}-${{ env.USE_PYTHON_VERSION }}/bin" >> $GITHUB_ENV

        # GITHUB_PATH does not seem to have any effect inside a container!

        # Add python to the path
        echo "/opt/python/${{ env.USE_PYTHON_VERSION }}-${{ env.USE_PYTHON_VERSION }}/bin" >> $GITHUB_PATH

    - name: Install Python Dependencies
      run: |

        # Install build dependencies manually and use --no-build-isolation
        # We do this to avoid building against numpy 2 as the numpy version is
        # not specified in petsc4py's requires section
        pip install cython 'numpy<2' setuptools mkl==${{ vars.MKL_VERSION }} mkl-service
        pip install pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Install oneAPI MKL
      run: |

        MKL_NAME=l_onemkl_p_${{ vars.MKL_VERSION }}.664
        ONEAPI_DIR=${{ env.LIB_DIR }}/oneAPI

        # Download install script
        curl -O -L ${{ env.MKL_BASE_URL }}/${MKL_NAME}.sh

        # Install
        sh ./${MKL_NAME}.sh -a --silent --eula accept --install-dir=$ONEAPI_DIR

        # This sets a bunch of variables including MKLROOT, PKG_CONFIG_PATH
        source $ONEAPI_DIR/setvars.sh

        # expose the ones we need
        echo "MKLROOT=${MKLROOT}" >> $GITHUB_ENV
        # Add to PKG_CONFIG_PATH
        # echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> $GITHUB_ENV

    - name: Build MPICH
      run: |

        MPICH_NAME=mpich-${{ vars.MPICH_VERSION }}
        MPICH_TAR=${MPICH_NAME}.tar.gz
        MPICH_URL=https://www.mpich.org/static/downloads/${{ vars.MPICH_VERSION }}/${MPICH_TAR}
        MPICH_ROOT_DIR=${{ env.LIB_DIR }}/${MPICH_NAME}
        MPICH_BUILD_DIR=${MPICH_ROOT_DIR}/build
        MPICH_INSTALL_DIR=${MPICH_ROOT_DIR}/install

        curl -O -L ${MPICH_URL}
        tar -xzf ${MPICH_TAR} -C ${{ env.LIB_DIR }}

        mkdir ${MPICH_BUILD_DIR}
        mkdir ${MPICH_INSTALL_DIR}

        cd ${MPICH_BUILD_DIR}

        # enable-fast=all/yes sets O2,ndebug,alwaysinline

        ../configure \
          CFLAGS=${MPICH_FLAGS} \
          CXXFLAGS=${MPICH_FLAGS} \
          FCLAGS=${MPICH_FLAGS} \
          FFLAGS=${MPICH_FLAGS} \
          --prefix=${MPICH_INSTALL_DIR} \
          --enable-fast=all \
          --with-device=ch3:nemesis \
          --with-pm=hydra \
          --with-hwloc=embedded \
          --disable-maintainer-mode \
          --disable-dependency-tracking

        make
        make install

        echo "MPICH_INSTALL_DIR=${MPICH_INSTALL_DIR}" >> $GITHUB_ENV
        # echo "PKG_CONFIG_PATH=${MPICH_INSTALL_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH}" >> $GITHUB_ENV


    - name: Build PETSc
      run: |

        # PETSC
        PETSC_NAME=petsc-${{ vars.PETSC_VERSION }}
        PETSC_TAR=${PETSC_NAME}.tar.gz
        PETSC_URL=https://web.cels.anl.gov/projects/petsc/download/release-snapshots/${PETSC_TAR}
        PETSC_DIR=${{ env.LIB_DIR }}/${PETSC_NAME}

        curl -O -L ${PETSC_URL}
        tar -xzf ${PETSC_TAR} -C ${{ env.LIB_DIR }}
        cd ${PETSC_DIR}

        # configure
        # PETSC_ARCH can be referenced as ${{ env.PETSC_ARCH }} or $PETSC_ARCH
        python configure \
        --PETSC_ARCH=${PETSC_ARCH} \
        --COPTFLAGS=${PETSC_FLAGS} \
        --CXXOPTFLAGS=${PETSC_FLAGS} \
        --FOPTFLAGS=${PETSC_FLAGS} \
        --with-x=0 \
        --with-debugging=0 \
        --with-fortran-bindings=0 \
        --with-mpi=1 \
        --with-mpi-dir=${MPICH_INSTALL_DIR} \
        --with-hypre=1 \
        --download-hypre \
        --with-blaslapack-dir=${MKLROOT} \
        --with-mkl_pardiso-dir=${MKLROOT} \
        --with-shared-library=1

        make all
        make check

        echo "PETSC_DIR=${PETSC_DIR}" >> $GITHUB_ENV
        echo "PETSC4PY_DIR=${PETSC_DIR}/src/binding/petsc4py" >> $GITHUB_ENV

        # add to PKG_CONFIG_PATH
        # echo "PKG_CONFIG_PATH=${PETSC_DIR}/${PETSC_ARCH})/lib/pkgconfig:${PKG_CONFIG_PATH}" >> $GITHUB_ENV

    - name: Build wheel for petsc4py
      run: |

        echo "Using PETSC_DIR   ${PETSC_DIR}"
        echo "Using PETSC_ARCH  ${PETSC_ARCH}"

        WHEEL_DIR=${PETSC4PY_DIR}/wheelhouse

        # petsc4py reads configuration etc. from
        # ${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables

        python -m pip wheel -v --no-deps --no-build-isolation -w ${WHEEL_DIR} ${PETSC4PY_DIR}

        # env vars defined by manylinux:
        # AUDITWHEEL_PLAT = AUDITWHEEL_POLICY + AUDITWHEEL_ARCH
        auditwheel repair \
          --exclude libmkl_core.so.2 \
          --exclude libmkl_intel_lp64.so.2 \
          --exclude libmkl_gnu_thread.so.2 \
          -w ${WHEEL_DIR} ${WHEEL_DIR}/*.whl

        # Filename of the fixed wheel
        PACKAGE_TAG="petsc4py-${{ vars.PETSC_VERSION }}"
        PYTHON_ABI_TAG="${{ env.USE_PYTHON_VERSION }}-${{ env.USE_PYTHON_VERSION }}"
        WHEEL_FILENAME=${WHEEL_DIR}/${PACKAGE_TAG}-${PYTHON_ABI_TAG}-${AUDITWHEEL_PLAT}.whl

        # Fix rpaths in wheel: unpack, fix, pack
        python -m wheel unpack ${WHEEL_FILENAME} -d ${WHEEL_DIR}

        # Enable link with MKL pypi package
        # add rpath entry to .../lib/
        # from .../lib/pythonX.Y/site-packages/petsc4py/lib/arch-X/
        patchelf --add-rpath \$ORIGIN/../../../../.. ${WHEEL_DIR}/${PACKAGE_TAG}/petsc4py/lib/${PETSC_ARCH}/PETSc*.so
        # from .../lib/pythonX.Y/site-packages/petsc4py.libs/
        patchelf --add-rpath \$ORIGIN/../../.. ${WHEEL_DIR}/${PACKAGE_TAG}/petsc4py.libs/libpetsc*
        patchelf --add-rpath \$ORIGIN/../../.. ${WHEEL_DIR}/${PACKAGE_TAG}/petsc4py.libs/libHYPRE*

        # it seems that libmpifort does not get $ORIGIN in rpath although it
        # requires pciaccess, so fix that
        patchelf --set-rpath \$ORIGIN ${WHEEL_DIR}/${PACKAGE_TAG}/petsc4py.libs/libmpi*

        # pack the modified wheel
        python -m wheel pack ${WHEEL_DIR}/${PACKAGE_TAG} -d ${WHEEL_DIR}

        echo "WHEEL_DIR=${WHEEL_DIR}" >> $GITHUB_ENV
        echo "WHEEL_FILENAME=${WHEEL_FILENAME}" >> $GITHUB_ENV

    - name: Install petsc4py
      run: python -m pip install ${WHEEL_FILENAME}

  # test:
  #   needs: build

    - name: Running tests shipped with petsc4py
      run: python ${PETSC4PY_DIR}/test/runtests.py --summary

    - name: Running internal tests
      run: pytest tests

  # publish:
  #   needs: build

  #   steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      # if: !startsWith(github.ref, 'refs/tags/')
      with:
        name: linux-wheels
        path: "${{ env.WHEEL_DIR }}/*${{ vars.MANYLINUX_PLATFORM }}.whl"

    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: wheelhouse/*.whl

        # body_path: CHANGELOG.md
        # repository: my_gh_org/my_gh_repo
        # # note you'll typically need to create a personal access token
        # # with permissions to create releases in the other repo
        # token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}


    # - name: Upload to PyPI
    #   if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
    #   run: |
    #     $PYTHON -m pip install twine
    #     $PYTHON -m twine upload wheelhouse/*.whl -u __token__ -p "$PASSWORD"
    #   env:
    #     PASSWORD: ${{ secrets.PYPI_TOKEN }}
    #     PYTHON: /opt/python/cp38-cp38/bin/python
